### ISSUE TITLE
Sticky menu for blog posts

### ISSUE THREAD

**Issue by pquerner** [pmoreno-rodriguez/grav-theme-future2021#45]
Is a sticky menu planned? ie. left for long blog posts
Like the mini-post sidemenu, but stickied, and with information from the post, like "table of contents"

**Comment by pmoreno-rodriguez** [comment]
Hi @pquerner.
I will take a look. I assume you mean something like this:
[https://wowthemesnet.github.io/mundana-theme-jekyll/](https://wowthemesnet.github.io/mundana-theme-jekyll/)

**Comment by pquerner** [comment]
Yea, exactly. Maybe this could be useful? Idk, tell me what you think. :)

**Comment by pmoreno-rodriguez** [comment]
Hi.

I've been testing some css change for the sidebar with the position: sticky property, and it works fine, but all this does is leave the sidebar fixed by scrolling the body of the page.

I'm thinking that it might be better for users to offer the ability to sidebar a list of recently published articles, instead of featured articles, or both, in the Blog template. To do this you would have to create a new partial template, but this would be an option with more alternatives than simply setting the sidebar position to fixed.

I won't be able to make these changes as quickly as on other occasions, but I'll write it down on my to-do list and choose one of these proposals.

**Comment by pmoreno-rodriguez** [comment]
Hi @pquerner. I've just released a new version of theme Future2021, with a new template with the recent posts, customizable in theme options.

At the moment, I think this is better than sticky section in sidebar because the latter has some issues with theme's CSS styles.

**Comment by pmoreno-rodriguez** [comment]
However there is a plugin in Grav repository for a table of contents in long posts.

This is the link: [https://github.com/trilbymedia/grav-plugin-page-toc](https://github.com/trilbymedia/grav-plugin-page-toc)

**Comment by pmoreno-rodriguez** [comment]
Hi @pquerner 

Can you test the latest version of theme, in the [README](http://future.juanvillen.es/readme) page (in demo version), with a table of contents in a large page. 

I've included support for [Page Toc](https://github.com/trilbymedia/grav-plugin-page-toc) plugin.

I think it's that what you suggested.

**Comment by pquerner** [comment]
Wonderful. Thats exactly how I pictured it! :)
