### ISSUE TITLE
Can't disable social icons completely

### ISSUE THREAD

**Issue by millerfield** [pmoreno-rodriguez/grav-theme-future2021#6]
This happens on 1.0.1 and 1.0.2 as well.
Setup: Grav v1.7.37.1 with Admin v1.10.36 in a Docker container.
Go to Themes -> Future 2021 configuration page.
Under social icons, when deleting all social icons, all of them (Twitter, FB, Instagram) will reappear.
Leaving just one is the least worse case if you not plan to use any social icons.

**Comment by pmoreno-rodriguez** [comment]
I think it's due to some bug in Grav, since it should use the future2021.yaml file from the config/themes folder, before the one in the theme's root folder.
I have changed the future2021.yaml file in the development branch. Please use instead the config/themes/future2021.yaml file to have the sample content and replace the future2021.yaml file from the theme root

**Comment by pmoreno-rodriguez** [comment]
Fixed in develop branch.
